# Generated by Django 5.1.2 on 2024-11-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('tar_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(db_column='tar_descricao', max_length=255)),
                ('setor', models.CharField(db_column='tar_setor', max_length=100)),
                ('prioridade', models.CharField(db_column='tar_prioridade', max_length=20)),
                ('status', models.CharField(db_column='tar_status', max_length=20)),
                ('data', models.DateField(db_column='tar_data')),
            ],
            options={
                'db_table': 'tbl_tarefas',
            },
        ),
    ]
