# Generated by Django 5.1.2 on 2024-11-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_tarefa_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], db_column='tar_prioridade', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], db_column='tar_status', max_length=20),
        ),
    ]
