# Generated by Django 5.1.2 on 2024-11-21 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_user_tarefa_usuario_alter_tarefa_prioridade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='usuario',
            new_name='user',
        ),
    ]
